-- MySQL Script generated by MySQL Workbench
-- Thu Nov 19 09:41:02 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_chat
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bd_chat` ;

-- -----------------------------------------------------
-- Schema bd_chat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_chat` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci ;
USE `bd_chat` ;

-- -----------------------------------------------------
-- Table `bd_chat`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_chat`.`usuario` ;

CREATE TABLE IF NOT EXISTS `bd_chat`.`usuario` (
  `nombre` VARCHAR(45) NOT NULL,
  `nombre_completo` VARCHAR(60) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  `ultimoAcceso` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_chat`.`mensaje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_chat`.`mensaje` ;

CREATE TABLE IF NOT EXISTS `bd_chat`.`mensaje` (
  `secuencia` INT(24) NOT NULL AUTO_INCREMENT,
  `usuario_emisor` VARCHAR(45) NOT NULL,
  `usuario_receptor` VARCHAR(45) NOT NULL,
  `fecha` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `texto` TEXT NOT NULL,
  `enviado` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`secuencia`),
  INDEX `fk_mensaje_emisor_idx` (`usuario_emisor` ASC) VISIBLE,
  INDEX `fk_mensaje_receptor_idx` (`usuario_receptor` ASC) VISIBLE,
  CONSTRAINT `fk_mensaje_emisor`
    FOREIGN KEY (`usuario_emisor`)
    REFERENCES `bd_chat`.`usuario` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mensaje_receptor`
    FOREIGN KEY (`usuario_receptor`)
    REFERENCES `bd_chat`.`usuario` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
